# Generated by Django 5.0.7 on 2024-07-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0002_producto_cantidad_inicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='cantidad_almacen',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_tienda',
            field=models.IntegerField(default=0),
        ),
    ]
