# Generated by Django 5.0.7 on 2024-07-31 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0003_rename_cantidad_producto_cantidad_almacen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ubicacion_almacen',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
