# Generated by Django 5.0.7 on 2024-08-05 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0005_alter_producto_cantidad_almacen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='cif',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
